/// Represents a power-saving tip generated by the Tips Engine
/// WHY: Encapsulates tip metadata for UI rendering and analytics
class PowerSavingTip {
  final String message;
  final String? applianceName; // Nullable: generic tips have no appliance
  final double? estimatedSavings; // In units/day (nullable for non-quantified tips)
  final TipType tipType;

  PowerSavingTip({
    required this.message,
    this.applianceName,
    this.estimatedSavings,
    required this.tipType,
  });

  /// Convert to map for analytics (optional)
  Map<String, dynamic> toAnalyticsMap() {
    return {
      'tip_type': tipType.name,
      'has_appliance': applianceName != null,
      'has_savings': estimatedSavings != null,
    };
  }

  @override
  String toString() => 'PowerSavingTip($tipType: $message)';
}

/// Categories of tips for filtering/prioritization
enum TipType {
  /// Coverage is less than 5 days
  lowCoverage,

  /// Burn rate exceeds 20 units/day
  highBurn,

  /// Budget insufficient for desired duration
  insufficientBudget,

  /// Appliance-specific optimization suggestion
  applianceOptimization,

  /// Generic power-saving advice
  generic,
}

extension TipTypeExtension on TipType {
  /// Icon for UI display
  String get icon {
    switch (this) {
      case TipType.lowCoverage:
        return '⚠️';
      case TipType.highBurn:
        return '🔥';
      case TipType.insufficientBudget:
        return '💰';
      case TipType.applianceOptimization:
        return '💡';
      case TipType.generic:
        return 'ℹ️';
    }
  }

  /// Priority for sorting (lower = higher priority)
  int get priority {
    switch (this) {
      case TipType.lowCoverage:
        return 1;
      case TipType.insufficientBudget:
        return 2;
      case TipType.highBurn:
        return 3;
      case TipType.applianceOptimization:
        return 4;
      case TipType.generic:
        return 5;
    }
  }
}